// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/inference/v1/inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_SUCCEEDED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_SUCCEEDED",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_SUCCEEDED":   3,
		"JOB_STATUS_FAILED":      4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inference_v1_inference_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_inference_v1_inference_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Status        JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=inference.v1.JobStatus" json:"status,omitempty"`
	Result        *string                `protobuf:"bytes,4,opt,name=result,proto3,oneof" json:"result,omitempty"`
	FailureReason *string                `protobuf:"bytes,5,opt,name=failure_reason,json=failureReason,proto3,oneof" json:"failure_reason,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_inference_v1_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_v1_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_inference_v1_inference_proto_rawDescGZIP(), []int{4}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

func (x *Job) GetFailureReason() string {
	if x != nil && x.FailureReason != nil {
		return *x.FailureReason
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_inference_v1_inference_proto protoreflect.FileDescriptor

const file_proto_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\"proto/inference/v1/inference.proto\x12\finference.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x10SubmitJobRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"5\n" +
	"\x0eGetJobResponse\x12#\n" +
	"\x03job\x18\x01 \x01(\v2\x11.inference.v1.JobR\x03job\"\xbb\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.inference.v1.JobStatusR\x06status\x12\x1b\n" +
	"\x06result\x18\x04 \x01(\tH\x00R\x06result\x88\x01\x01\x12*\n" +
	"\x0efailure_reason\x18\x05 \x01(\tH\x01R\rfailureReason\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\t\n" +
	"\a_resultB\x11\n" +
	"\x0f_failure_reason*\x88\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x042\xa9\x01\n" +
	"\x10InferenceService\x12N\n" +
	"\tSubmitJob\x12\x1e.inference.v1.SubmitJobRequest\x1a\x1f.inference.v1.SubmitJobResponse\"\x00\x12E\n" +
	"\x06GetJob\x12\x1b.inference.v1.GetJobRequest\x1a\x1c.inference.v1.GetJobResponse\"\x00BJZHgithub.com/DavidOrtegaFarrerons/infergrid/proto/inference/v1;inferencev1b\x06proto3"

var (
	file_proto_inference_v1_inference_proto_rawDescOnce sync.Once
	file_proto_inference_v1_inference_proto_rawDescData []byte
)

func file_proto_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_proto_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_proto_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inference_v1_inference_proto_rawDesc), len(file_proto_inference_v1_inference_proto_rawDesc)))
	})
	return file_proto_inference_v1_inference_proto_rawDescData
}

var file_proto_inference_v1_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_inference_v1_inference_proto_goTypes = []any{
	(JobStatus)(0),                // 0: inference.v1.JobStatus
	(*SubmitJobRequest)(nil),      // 1: inference.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),     // 2: inference.v1.SubmitJobResponse
	(*GetJobRequest)(nil),         // 3: inference.v1.GetJobRequest
	(*GetJobResponse)(nil),        // 4: inference.v1.GetJobResponse
	(*Job)(nil),                   // 5: inference.v1.Job
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_inference_v1_inference_proto_depIdxs = []int32{
	5, // 0: inference.v1.GetJobResponse.job:type_name -> inference.v1.Job
	0, // 1: inference.v1.Job.status:type_name -> inference.v1.JobStatus
	6, // 2: inference.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: inference.v1.Job.updated_at:type_name -> google.protobuf.Timestamp
	1, // 4: inference.v1.InferenceService.SubmitJob:input_type -> inference.v1.SubmitJobRequest
	3, // 5: inference.v1.InferenceService.GetJob:input_type -> inference.v1.GetJobRequest
	2, // 6: inference.v1.InferenceService.SubmitJob:output_type -> inference.v1.SubmitJobResponse
	4, // 7: inference.v1.InferenceService.GetJob:output_type -> inference.v1.GetJobResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_inference_v1_inference_proto_init() }
func file_proto_inference_v1_inference_proto_init() {
	if File_proto_inference_v1_inference_proto != nil {
		return
	}
	file_proto_inference_v1_inference_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inference_v1_inference_proto_rawDesc), len(file_proto_inference_v1_inference_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_proto_inference_v1_inference_proto_depIdxs,
		EnumInfos:         file_proto_inference_v1_inference_proto_enumTypes,
		MessageInfos:      file_proto_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_proto_inference_v1_inference_proto = out.File
	file_proto_inference_v1_inference_proto_goTypes = nil
	file_proto_inference_v1_inference_proto_depIdxs = nil
}
